env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    ssh1: "ENCRYPTED[216b9abcc86873d7d3220252793bc1433cde0e9674238a5f519f0f053391858fc306c319cb3e285244d3a0009dcf8ae5]"
    ssh2: "ENCRYPTED[1417cb00780f640e025ec5b354c221dd7d050682031161790bc6729f09b76c965451f52c2d6824cdee787577486949c3]"

task:
  name: Build_Upload
  timeout_in: 2h
  container:
    image: alpine/git
    cpu: .7
    memory: 1G
  config_script:
    - git config --global user.name "dopaemon"
    - git config --global user.email "polarisdp@gmail.com"
    - mkdir -p ~/.ssh
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - touch ~/.ssh/id_ed25519.pub
    - touch ~/.ssh/id_ed25519
    - echo "$ssh2" > ~/.ssh/id_ed25519.pub
    - echo "$ssh1" > ~/.ssh/id_ed25519
  git_script:
    - git clone git@github.com:KernelPanic-OpenSource/KernelPanic-OpenSource.github.io.git ~/Repo
    - git clone https://github.com/dopaemon/KernelPanicPage ~/Repo1
  build_script:
    - cd ~/Repo
    - rm -rvf Packages.bz2
    - git rm Packages.bz2
    - bzip2 -zvk Packages
    - touch loop
    - echo "Loading..." >> loop
    - git add -v -A
    - git commit -sm "Update Packages"
  push_script:
    - cd ~/Repo
    - echo "yes" | git push -f origin master
  loop_script:
    - cd ~/Repo1
    - touch loop
    - echo "Loading..." >> loop
    - git add -v -A
    - git commit -sm "LoopCI"    
    - echo "yes" | git push -f origin master    
